"""
Provenance falsifier for SGN.

SPECIFICATION (frozen 2026-09-30, before any change for row 6b):

    Every quantitative value presented as an SGN result must be derivable
    from a committed machine-readable artifact generated by the simulator.

    The chain required is

        simulator -> metrics.json -> reconciliation -> published table

    and a hand-edit of any published value must be detected.

This file is the pre-fix falsifier for row 6b. It was executed against the
state left by the row-6 codec repair and it failed. See FALSIFIER-LOG-6b.md.

Distinct from tests/test_sgn_roundtrip.py, which establishes that the codec is
invertible. Row 6 passing does not license any claim that a published number is
correct. A repair does not inherit the validity of another repair.
"""

import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
METRICS = os.path.join(ROOT, "figures", "metrics.json")
README = os.path.join(ROOT, "README.md")
RECONCILER = os.path.join(ROOT, "tools", "reconcile_readme.py")


def count_numbers(obj):
    """Count numeric leaves anywhere in a JSON structure."""
    if isinstance(obj, dict):
        return sum(count_numbers(v) for v in obj.values())
    if isinstance(obj, list):
        return sum(count_numbers(v) for v in obj)
    if isinstance(obj, bool):
        return 0
    if isinstance(obj, (int, float)):
        return 1
    return 0


def readme_table():
    """Extract the published results table from README.md as a list of rows."""
    with open(README) as handle:
        lines = handle.read().splitlines()

    rows, in_table = [], False
    for line in lines:
        if line.startswith("| Method |") and "Bit Acc" in line:
            in_table = True
            continue
        if in_table:
            if not line.startswith("|"):
                break
            if re.match(r"^\|[\s:\-|]+\|$", line):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            rows.append(cells)
    return rows


def published_numbers():
    """Every numeric token appearing in the published table."""
    values = []
    for row in readme_table():
        for cell in row[3:]:  # skip method, domain, PSNR-adjacent labels
            try:
                values.append((row[0], float(cell)))
            except ValueError:
                values.append((row[0], cell))  # non-numeric, e.g. a range
    return values


def main():
    failures = []
    print("=" * 78)
    print("PROVENANCE FALSIFIER — row 6b")
    print("property: every published value derives from a committed numeric artifact")
    print("=" * 78)

    # --- F1: the artifact must contain numbers --------------------------------
    if not os.path.exists(METRICS):
        print("  [FAIL] F1 metrics.json exists")
        failures.append("F1-missing")
    else:
        with open(METRICS) as handle:
            metrics = json.load(handle)
        n = count_numbers(metrics)
        if n == 0:
            print(f"  [FAIL] F1 metrics.json contains numeric values: found {n}")
            failures.append("F1-no-numbers")
        else:
            print(f"  [PASS] F1 metrics.json contains {n} numeric values")

    # --- F2: every published value must be derivable --------------------------
    derived = False
    if os.path.exists(RECONCILER):
        print("  [PASS] F2a reconciliation script present")
        derived = True
    else:
        print("  [FAIL] F2a reconciliation script present: tools/reconcile_readme.py absent")
        failures.append("F2-no-reconciler")

    if derived:
        sys.path.insert(0, os.path.join(ROOT, "tools"))
        import reconcile_readme  # noqa: E402

        expected = reconcile_readme.table_markdown(
            json.load(open(METRICS))
        )
        with open(README) as handle:
            body = handle.read()
        if expected.strip() not in body:
            print("  [FAIL] F2b published table equals the generated table")
            failures.append("F2-table-mismatch")
        else:
            print("  [PASS] F2b published table equals the generated table")
    else:
        print("  [FAIL] F2b published table is generated from the artifact: no chain exists")
        failures.append("F2-no-chain")

    # --- F3: a hand-edit must be detected -------------------------------------
    if derived:
        with open(README) as handle:
            original = handle.read()
        try:
            with open(METRICS) as handle:
                metrics = json.load(handle)
            expected = reconcile_readme.table_markdown(metrics).strip()

            # Tamper generically. An earlier version of this test replaced the
            # literal "| 0.50 |", which existed only because that was the
            # published value at the time. The codec repair changed it to
            # "| 1.00 |", so the literal was already down to two occurrences
            # and would have disappeared entirely had the artifact produced
            # 1.00 for every method — at which point the test would have failed
            # for the wrong reason. A check must not depend on the value it is
            # checking. This perturbs each data row in turn instead.
            rows = [
                line for line in original.splitlines()
                if line.startswith("| ")
                and "Method" not in line
                and not re.match(r"^\|[\s:\-|]+\|$", line)
            ]
            if not rows:
                print("  [FAIL] F3 rows found in the published table")
                failures.append("F3-no-rows")
            else:
                undetected = []
                for row in rows:
                    method = row.split("|")[1].strip()
                    cells = row.split("|")
                    cells[3] = " 99.9 "          # perturb the PSNR cell
                    tampered = original.replace(row, "|".join(cells))
                    if expected in tampered:
                        undetected.append(method)

                if undetected:
                    print(f"  [FAIL] F3 hand-edit detected for all rows; missed: "
                          f"{', '.join(undetected)}")
                    failures.append("F3-hand-edit-undetected")
                else:
                    print(f"  [PASS] F3 a hand-edited value is detected "
                          f"({len(rows)} rows perturbed)")
        finally:
            with open(README, "w") as handle:
                handle.write(original)
    else:
        print("  [FAIL] F3 a hand-edited published value is detected: nothing to compare against")
        failures.append("F3-no-mechanism")

    print("-" * 78)
    if failures:
        print(f"FAILED: {len(failures)} assertion(s) — {', '.join(failures)}")
        return 1
    print("PASSED: all provenance assertions hold")
    return 0


if __name__ == "__main__":
    sys.exit(main())
